default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: [
          "--application-directories",
          ":app",
        ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.291'
    hooks:
      - id: ruff
        args: [ "--config", "pyproject.toml", "--fix", "--show-fixes" ]

  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: [ "--settings-file", "pyproject.toml" ]

  - repo: https://github.com/psf/black
    rev: '23.9.1'
    hooks:
      - id: black
        args: [ "--config", "pyproject.toml" ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ --in-place, -r ]
